name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [default]
        include:
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            cxx_compiler: g++
          - os: ubuntu-latest
            compiler: clang
            c_compiler: clang
            cxx_compiler: clang++
          - os: windows-latest
            compiler: msvc
          - os: macos-latest
            compiler: clang
            c_compiler: clang
            cxx_compiler: clang++
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.14.x'
    
    - name: Set up compilers (Linux)
      if: runner.os == 'Linux' && matrix.c_compiler
      run: |
        echo "CC=${{ matrix.c_compiler }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.cxx_compiler }}" >> $GITHUB_ENV
    
    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
    
    - name: Configure CMake (Unix)
      if: runner.os != 'Windows'
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
    
    - name: Build
      run: |
        cmake --build build --config Release
  

